apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bsn1xq6ac-java-quarkus
  janus-idp.io/tekton: bsn1xq6ac-java-quarkus
  backstage.io/kubernetes-id: bsn1xq6ac-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bsn1xq6ac-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
